#!/system/bin/sh

# hsu - Hide su and Magisk binaries to prevent programs from reading the binaries using "ls"
# Copyright (C) 2020 xaedoplay @ XDA
# Licensed under the GNU General Public License v2.0

# Functions file for hsu
# Note: Always return to main menu using the "oobecheck" function

ADBPATH=/data/adb
MAGISKPATH=$ADBPATH/magisk
MMODPATH=$ADBPATH/modules/hsu
BBPATH=$ADBPATH/magisk/busybox
ENVPATH=$ADBPATH/.hsu
HSUFSPATH=$ENVPATH/hsu_fs
MODVER=PRERELEASE

if [ -f "$BBPATH" ]; then
	for ITEM in $($BBPATH --list | tail -n +3); do
		alias $ITEM="$BBPATH $ITEM"
	done
fi

# Common functions

# Header text
	# Line divider
	LINEDIV="====================================="
	# END Line divider
menuheader () {
	if [ -z "$ANDROID_SOCKET_adbd" ]; then
		clear
	fi
	echo ""
	echo -e "hsu version $MODVER, Copyright (C) xaedoplay @ XDA"
	echo -e "\nHide Magisk and root system-wide to prevent any kinds of detection"
	echo -e "\nLicensed under the GNU General Public License v2.0\nhsu comes with ABSOLUTELY NO WARRANTY"
	echo ""
	echo -e $LINEDIV
	echo -e "$1"
	echo -e $LINEDIV
}

# Check if environment exists
oobecheck () {
	if [ -d "$ENVPATH" ]; then
		mainprompt
	else
		oobeprompt
	fi
}
# Environment initializer REWORKED
initenv () {
	menuheader "Environment initialization"
	mkdir -p "$ENVPATH"
	if [ -d "$ENVPATH" ] ; then
		echo -e "\nEnvironment initialized. Initializing mirror image..."
		initenv_img
	else
		echo -e "\nAn error occured while initializing environment. Exiting...\n"
		echo -e "$LINEDIV"
		exit 1
	fi
}
	# Environment initializer - imager
	initenv_img () {
		mkdir -p $HSUFSPATH/images
		dd if=/dev/zero of=$HSUFSPATH/images/sbin.img bs=4096 count=32768
		mkfs.ext4 $HSUFSPATH/images/sbin.img
		mkdir -p $HSUFSPATH/images/mirrors
		tar -ch --exclude=*magisk* --exclude=*su* --exclude=resetprop /sbin/. | tar -x -C $HSUFSPATH/images/mirrors/
		if [ "$SESTAT" = 0 ] ; then
			mkdir -p $HSUFSPATH/images/mount_sbin
			mount -w /data/adb/.hsu/hsu_fs/images/sbin.img $HSUFSPATH/images/mount_sbin
			tar -ch -C $HSUFSPATH/images/mirrors/sbin/ . | tar -x -C $HSUFSPATH/images/mount_sbin/
			umount $HSUFSPATH/images/mount_sbin
			echo -e "\nSuccessfully initialized mirror image. Returning to main menu..."
			oobecheck
		elif [ "$SESTAT" = 1 ] ; then
			echo -e "SELinux enforcing mode detected! Setting to permissive SELinux..."
			setenforce 0
			mkdir -p $HSUFSPATH/images/mount_sbin
			mount -w /data/adb/.hsu/hsu_fs/images/sbin.img $HSUFSPATH/images/mount_sbin
			tar -ch -C $HSUFSPATH/images/mirrors/sbin/ . | tar -x -C $HSUFSPATH/images/mount_sbin/
			umount $HSUFSPATH/images/mount_sbin
			setenforce 1
			echo -e "Restoring SELinux enforcing..."
			echo -e "\nSuccessfully initialized mirror image. Returning to main menu..."
			oobecheck
		else
			echo -e "\nInvalid SELinux status. Exiting..."
			exit 1
		fi
	}

# SELinux status readback
selinux_stat () {
	if [ "$(getenforce)" = "Enforcing" ] ; then
		SESTAT="1"
	elif [ "$(getenforce)" = "Permissive" ] ; then
		SESTAT="0"
	else
		SESTAT="ERROR"
	fi
}

# Root and magisk hide
hideroot () {
	if [ -e $HSUFSPATH/images/sbin.img ]; then
		hideroot_exec
	else
		echo -e "Environment not initialized (properly) yet! Please do so by starting hsu without any arguments."
		exit 1
	fi
}

	# Execute instructions REWORK
	hideroot_exec () {
		menuheader "Magisk and root hide\n\nThis does disable and hide Magisk and root until interrupted\n$LINEDIV\nWarning! If the shell session got abruptly terminated (which is really rare to happen), you will have to do a reboot to re-enable Magisk and root."
		echo -e "\nInitializing Magisk and root hide..."
		if [ "$SESTAT" = 0 ] ; then
			mount -r /data/adb/.hsu/hsu_fs/images/sbin.img /sbin
			echo -e "\nMagisk and root hide started."
			echo -e "\nInput any key to interrupt and stop"
			read -rsn 1
				umount /sbin
			menuheader "Magisk and root hide\n\nThis does disable and hide Magisk and root until interrupted\n$LINEDIV\nWarning! If the shell session got abruptly terminated (which is really rare to happen), you will have to do a reboot to re-enable Magisk and root."
			echo -e "\nMagisk and root hide was interrupted and stopped.\n\nInput any key to return to main menu"
			read -rsn 1
				oobecheck
		elif [ "$SESTAT" = 1 ] ; then
			echo -e "SELinux enforcing mode detected! Setting to permissive SELinux..."
			setenforce 0
			mount -r /data/adb/.hsu/hsu_fs/images/sbin.img /sbin
			echo -e "\nMagisk and root hide started."
			echo -e "\nInput any key to interrupt and stop"
			read -rsn 1
				umount /sbin
			setenforce 1
			menuheader "Magisk and root hide\n\nThis does disable and hide Magisk and root until interrupted\n$LINEDIV\nWarning! If the shell session got abruptly terminated (which is really rare to happen), you will have to do a reboot to re-enable Magisk and root."
			echo -e "\nMagisk and root hide was interrupted and stopped.\n\nInput any key to return to main menu"
			read -rsn 1
				oobecheck
		else
			echo -e "\nInvalid SELinux status. Exiting..."
			exit 1
		fi
	}
# Clear module environment
clearenv () {
	menuheader "Clear module environment\n\nThis will clear the environment used by the module to hide Magisk and root. Recommended to do if you just updated this device."
	while true; do
		echo -e "\nDo you wish to clear the module environment (y)es or (n)o? (case-insensitive)"
		read yn
		if [ "$yn" != "${yn#[Yy]}" ] ; then
			clearenv_exec
		elif [ "$yn" != "${yn#[Nn]}" ] ; then
			oobecheck
		else
			echo -e "Invalid input $yn. Please enter your choice"
		fi
	done
	echo -e "If you read this message, there's a bug within the function\nPlease file an issue on GitHub, or even better, try and fix the bug yourself and open a pull request on GitHub."
	exit 1
}
	# Execute clear module environment
	clearenv_exec () {
		echo -e "Clearing the module environment..."
		rm -rf $ENVPATH
		oobecheck
	}

# Print usage help
helpf () {
	echo -e "hsu $MODVER by xaedoplay@XDA\nHide Magisk and root system-wide to prevent any kinds of detection\n"
	echo -e "Usage: $0 [help|hide]"
	echo -e "\thelp - Show this usage help"
	echo -e "\thide - Directly hide root and Magisk"
	exit 2
}

#TODO Autohide root when app is running
autohide () {
	menuheader "Autohide root and Magisk\n\nConfigure and enable process monitoring to disable and hide Magisk and root automatically when an app is running"
	echo -e "\nThis feature is not ready yet!\nInput any key to return to main menu"
	read -rsn 1
		oobecheck
}
